FROM ubuntu:14.04
MAINTAINER Atsushi Nagase<a@ngs.io>

RUN apt-get update -y && apt-get install -y software-properties-common
RUN apt-add-repository -y ppa:nginx/stable
RUN apt-add-repository -y ppa:brightbox/ruby-ng
RUN apt-get update -y && apt-get install -y \
    locales \
    language-pack-en \
    language-pack-en-base \
    openssh-server \
    curl \
    supervisor \
    build-essential \
    git-core \
    g++ \
    libcurl4-openssl-dev \
    libffi-dev \
    libmysqlclient-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2 \
    libxml2-dev \
    libxslt1-dev \
    libyaml-dev \
    python-software-properties \
    zlib1g-dev \
    ruby2.2-dev \
    ruby2.2

RUN gem install bundler --no-rdoc --no-ri

## Locales
RUN [ -f /var/lib/locales/supported.d/local ] || touch /var/lib/locales/supported.d/local
ADD docker/files/etc/default/locale /etc/default/locale
RUN dpkg-reconfigure --frontend noninteractive locales

ADD docker/files/etc/supervisor/supervisord.conf /etc/supervisor/supervisord.conf

ENV RAILS_ROOT=/var/www/app
COPY . $RAILS_ROOT
RUN cd $RAILS_ROOT && \
  bundle install --deployment --path /var/www/shared/vendor/bundle --without test development && \
  echo "SECRET_KEY_BASE=$(./bin/rake secret)" > .env && \
  echo "DATABASE_URL=<%= ENV['DATABASE_URL'] %>" >> .env
